### ISSUE TITLE
Unable to install on Arch

### ISSUE THREAD

**Issue by martmists** [noahbliss/Viper4Linux#19]
Output:
```bash
$ pacaur -S viper4linux-git 
:: Package viper4linux-git not found in repositories, trying AUR...
:: resolving dependencies...
:: no results found for gst-plugin-viper4linux (dependency tree: viper4linux-git gst-plugin-viper4linux)
```
Note that gst-plugin-viper4linux-git is available, but can't be installed since it can't find libviperfx, which is available as libviperfx-nonfree-bin

**Comment by noahbliss** [comment]
Going to assume this is resolved. Let me know if it persists.
