### ISSUE TITLE
Ubuntu 19.10 Eoan Viper stopped working

### ISSUE THREAD

**Issue by takobaba** [noahbliss/Viper4Linux#20]
Hey,

Viper4Linux stopped working on my ubuntu 19.10 setup.

here is the output i get on gui:

`root@tarik-latitude-7280:/opt/viper/Viper4Linux# viper-gui`
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`
`libpng warning: iCCP: known incorrect sRGB profile`
`Reloading...`
`Reloading App Config...`
`WRITE: ""`
`Looks like it was already dead...? Deleted pidfile.`
`You have to specify a module index or name`
`Unloaded Viper sink.`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Setting original sink to full volume...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Changing primary sink to Viper...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Moving existing audio streams to Viper...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`ERROR: Pipeline doesn't want to pause.`
`ERROR: from element /GstPipeline:pipeline0/GstPulseSink:pulsesink0: Failed to connect: Connection refused`
`Additional debug info:`
`pulsesink.c(614): gst_pulseringbuffer_open_device (): /GstPipeline:pipeline0/GstPulseSink:pulsesink0`
`WRITE: ""`
`Looks like it was already dead...? Deleted pidfile.`
`You have to specify a module index or name`
`Unloaded Viper sink.`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Setting original sink to full volume...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Changing primary sink to Viper...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`Moving existing audio streams to Viper...`
`Connection failure: Connection refused`
`pa_context_connect() failed: Connection refused`
`ERROR: Pipeline doesn't want to pause.`
`ERROR: from element /GstPipeline:pipeline0/GstPulseSink:pulsesink0: Failed to connect: Connection refused`
`Additional debug info:`
`pulsesink.c(614): gst_pulseringbuffer_open_device (): /GstPipeline:pipeline0/GstPulseSink:pulsesink0`

Dont know where to start troubleshooting, i ve uninstalled and re-installed following the steps on the main github documentation, no luck. still doesnt work.

thanks

**Comment by noahbliss** [comment]
Sorry for the delay on this! Have you tried running it without the GUI? It would at least allow us to divide and conquer.

**Comment by takobaba** [comment]
yes i have.

its the same:

> root@tarik-latitude-7280:/home/tarik# viper start
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> Setting original sink to full volume...
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> Changing primary sink to Viper...
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> Moving existing audio streams to Viper...
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> root@tarik-latitude-7280:/home/tarik# ERROR: Pipeline doesn't want to pause.
> ERROR: from element /GstPipeline:pipeline0/GstPulseSink:pulsesink0: Failed to connect: Connection refused
> Additional debug info:
> pulsesink.c(614): gst_pulseringbuffer_open_device (): /GstPipeline:pipeline0/GstPulseSink:pulsesink0
>
