### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by leonzon** [noahbliss/Viper4Linux#22]
when i run ./autogen.sh  
i get an  issue
autoreconf: Entering directory
autoreconf: configure.ac not using Gettext

I found a solution on another forum which suggested adding the following to the end of configure.ac

AM_GNU_GETTEXT_VERSION
AM_GNU_GETTEXT_REQUIRE_VERSION

whice leaves me with

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
autogen.sh failed

**Comment by yochananmarqos** [comment]
What Linux flavor? You need to have `gettext` installed which should be a part of your distro's build tools package; i.e., the `base-devel` group on Arch or `build-essential` on Ubuntu.

**Comment by leonzon** [comment]
linux mint 19.2
i just checked and both gettext and build-essential are installed. 
"
gettext is already the newest version (0.19.8.1-6ubuntu0.3).
build-essential is already the newest version (12.4ubuntu1).
"

**Comment by yochananmarqos** [comment]
What about `autopoint`? It should be part of `gettext`, but some idjit might have decided to export it to it's own package.

**Comment by leonzon** [comment]
ok, so that installed
i run ./autogen.sh and get

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
autogen.sh failed

if i add 
AM_GNU_GETTEXT_VERSION
AM_GNU_GETTEXT_REQUIRE_VERSION

to the configure.ac
i get this

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autopoint: *** Missing version: please specify in configure.ac through a line 'AM_GNU_GETTEXT_VERSION(x.yy.zz)' the gettext version the package is using
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
autogen.sh failed

I want to say that I appreciate your help but dont feel obliged to help me.
I can accept if it doesnt work for me & that I dont have the knowledge to get it working.

**Comment by yochananmarqos** [comment]
`aclocal` is one of `automake`'s binaries. Is `automake` installed?

`/usr/share/autoconf/Autom4te/FileUtils.pm` is owned by `autoconf`.

**Comment by leonzon** [comment]
that sorted it
thank you
