### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by YourSandwich** [noahbliss/Viper4Linux#27]
I used yay -S viper4linux-git and viper4linux-gui-git.
then configured device.conf with desc="Speakers" location=alsa_output.pci-0000_00_1f.3.analog-stereo
When started viper(viper start) gives this:

Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
WARNING: erroneous pipeline: no element "pulsesrc"

If asked for a status:
[ERROR]
There is a pidfile. However, there is no process running with the expected pid.
There is an idfile. The viper sink seems to be loaded at id: 29.

OS: Manjaro Linux

I Copied the text basicly form an other post because i have the same problem, but reboot didnt helped me. I also tried to delete the devices.conf file. didnt helped at all, i have this problem like for 1year on Manjaro KDE

**Comment by noahbliss** [comment]
We seem to be having issues with the Audio4Linux/Viper4Linux repo which is what the AUR version uses. In the meantime, a manual install using this repo's README should work. Feel free to report back. I'll leave this open.

**Comment by noahbliss** [comment]
@YourSandwich I just made a commit over there, if you can remove the packages and reinstall via the AUR, I'd be grateful.

**Comment by YourSandwich** [comment]
> @YourSandwich I just made a commit over there, if you can remove the packages and reinstall via the AUR, I'd be grateful.

It works, thank you i waited for at least a half year now. It was an bad idea not to submit the issue :)
