### ISSUE TITLE
You should recreate aclocal.m4 with macros from libtool 2.4.6

### ISSUE THREAD

**Issue by electrodragon** [noahbliss/Viper4Linux#28]
make command outputs this

make  all-recursive
make[1]: Entering directory '/home/atta/viper/gst-plugin-viperfx'
Making all in src
make[2]: Entering directory '/home/atta/viper/gst-plugin-viperfx/src'
/bin/sh ../libtool  --tag=CC --tag=disable-static  --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/orc-0.4  -Wall -g -O2 -Wall -MT libgstviperfx_la-gstviperfx.lo -MD -MP -MF .deps/libgstviperfx_la-gstviperfx.Tpo -c -o libgstviperfx_la-gstviperfx.lo `test -f 'gstviperfx.c' || echo './'`gstviperfx.c
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.42-b88ce-dirty.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[2]: *** [Makefile:458: libgstviperfx_la-gstviperfx.lo] Error 63
make[2]: Leaving directory '/home/atta/viper/gst-plugin-viperfx/src'
make[1]: *** [Makefile:400: all-recursive] Error 1
make[1]: Leaving directory '/home/atta/viper/gst-plugin-viperfx'
make: *** [Makefile:332: all] Error 2

**Comment by noahbliss** [comment]
I believe since the changes made by thepbone, we actually use cmake now. The updated repo for the gstreamer module should reflect this change.
