### ISSUE TITLE
A repo for openSUSE Leap 15.2?

### ISSUE THREAD

**Issue by perrsona1234** [noahbliss/Viper4Linux#29]
Hello.

I have seen on OBS, that there are packages available for Tumbleweed and Leap 15.1. Are there any plans on setting up a repo for 15.2 and future releases?

Thanks.

**Comment by noahbliss** [comment]
@fcuzzocrea comments?

**Comment by noahbliss** [comment]
@perrsona1234 feel like making one?

**Comment by fcuzzocrea** [comment]
I am sorry for missing the pinf. Anyway yes, I can switch on 15.2 builds too. To be honest, I should update also all the packages

**Comment by fcuzzocrea** [comment]
swtiched on. next time if I do not answer in a couple of days feel free to ping me on telegram

**Comment by noahbliss** [comment]
Sounds good thanks! Can you please use the Audio4Linux source code for those builds? I've been working to keep this one updated from time to time but main development will happen over there.

**Comment by fcuzzocrea** [comment]
Yeah, sure, will use those
