### ISSUE TITLE
readme.md: The double `git clone git clone`

### ISSUE THREAD

**Issue by NHKomaiha** [noahbliss/Viper4Linux#30]
Hey I noticed there's a small typo that might confuse linux newcomers 

in Manual section step 2
``` 
git clone git clone https://github.com/Audio4Linux/gst-plugin-viperfx    
```

which probably should be 
``` 
git clone https://github.com/Audio4Linux/gst-plugin-viperfx    
```

**Comment by noahbliss** [comment]
Oh geez you're right! Nice catch.

**Comment by noahbliss** [comment]
Fixed this with https://github.com/noahbliss/Viper4Linux/commit/2ca20c2a982f754abf9143eaa354dbe82ef22496

Thanks so much!
