### ISSUE TITLE
No package 'gstreamer-audio-1.0' found (debian 10)

### ISSUE THREAD

**Issue by onixd** [noahbliss/Viper4Linux#33]
-- Checking for modules 'gstreamer-1.0>=1.0;gstreamer-base-1.0>=1.0;gstreamer-controller-1.0>=1.0;gstreamer-audio-1.0>=1.0'
--   No package 'gstreamer-audio-1.0' found
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  CMakeLists.txt:8 (pkg_check_modules)

**Comment by noahbliss** [comment]
Picking this up here https://github.com/Audio4Linux/Viper4Linux/issues/8
