### ISSUE TITLE
Volume always resets to 100% upon reload

### ISSUE THREAD

**Issue by Node815** [noahbliss/Viper4Linux#34]
This has given us more jump scares than we would like.  Whenever I load Viper4Linux on my arch system, it does not respect my volume levels and instantly changes it to 100% which is quite loud.  I use some 120W Logitech speakers, so it is loud enough to wake up the dead!!!!  Other times, I can not get any sound upon launch and the only way to bring the sound is to do a reload through the app which then the volume maxes out.  

Is there a way to prevent this from happening other than ensuring my master volume on the speakers with the hardware volume control is down to zero??

**Comment by noahbliss** [comment]
This is a feature added in the audio4linux version of viper. Please give that a try.
