### ISSUE TITLE
Arch Compilation Error

### ISSUE THREAD

**Issue by moonlitopal** [noahbliss/Viper4Linux#40]
make command outputs this

make: Entering directory '/home/amnox/gst-plugin-viperfx/build'
[ 25%] Building C object CMakeFiles/gst-plugin-viperfx.dir/src/gstviperfx.c.o
In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
                 from /usr/include/glib-2.0/gobject/gbinding.h:31,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from /usr/include/gstreamer-1.0/gst/gstenumtypes.h:6,
                 from /usr/include/gstreamer-1.0/gst/gst.h:31,
                 from /home/amnox/gst-plugin-viperfx/src/gstviperfx.c:14:
/home/amnox/gst-plugin-viperfx/src/gstviperfx.c: In function ‘gst_viperfx_class_init’:
/usr/include/glib-2.0/gobject/gtype.h:2662:6: error: passing argument 1 of ‘gst_audio_filter_class_add_pad_templates’ from incompatible pointer type [-Wincompatible-pointer-types]
 2662 |     ((ct*) (void *) g_type_check_class_cast ((GTypeClass*) cp, gt))
/usr/include/glib-2.0/gobject/gtype.h:597:66: note: in expansion of macro ‘_G_TYPE_CCC’
  597 | #define G_TYPE_CHECK_CLASS_CAST(g_class, g_type, c_type)        (_G_TYPE_CCC ((g_class), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/home/amnox/gst-plugin-viperfx/src/gstviperfx.h:17:38: note: in expansion of macro ‘G_TYPE_CHECK_CLASS_CAST’
   17 | #define GST_VIPERFX_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST((klass) ,GST_TYPE_VIPERFX,GstviperfxClass))
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/amnox/gst-plugin-viperfx/src/gstviperfx.c:459:46: note: in expansion of macro ‘GST_VIPERFX_CLASS’
  459 |     gst_audio_filter_class_add_pad_templates(GST_VIPERFX_CLASS (klass), caps);
      |                                              ^~~~~~~~~~~~~~~~~
In file included from /usr/include/gstreamer-1.0/gst/audio/audio.h:109,
                 from /home/amnox/gst-plugin-viperfx/src/gstviperfx.c:17:
/usr/include/gstreamer-1.0/gst/audio/gstaudiofilter.h:99:73: note: expected ‘GstAudioFilterClass *’ {aka ‘struct _GstAudioFilterClass *’} but argument is of type ‘GstviperfxClass *’ {aka ‘struct _GstviperfxClass *’}
   99 | void    gst_audio_filter_class_add_pad_templates (GstAudioFilterClass * klass,
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/gst-plugin-viperfx.dir/build.make:90: CMakeFiles/gst-plugin-viperfx.dir/src/gstviperfx.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gst-plugin-viperfx.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
make: Leaving directory '/home/amnox/gst-plugin-viperfx/build'

**Comment by Colin130716** [comment]
How to fix it?I have the same problem.Thank you!
